enum Links {
  Login = "login",

  Home = "home",
  AboutUs = "about-us",
  ContactUs = "contact-us",
  Help = "help",
  TermsAndConditions = "terms-and-conditions",
  PrivacyAndPolicy = "privacy-and-policy",
  TelemedicinePolicy = "telemedicine-policy",
  MyChartManagement = "my-chart-management",
  PaymentSuccessful = "payment-successful",
  PaymentFailed = "payment-failed",
  SubscriptionCanceled = "cancel-successful",

  UserProfile = "user-profile",
  UserNotifications = "user-notifications",
  UserCases = "user-cases",
  UserChangePassword = "user-change-password",
  UserPhoneVerify = "user-phone-verify",
  UserInvoices = "user-invoices",
  UserChart = "user-chart",

  AdminPolicy = "admin-policy",
  AdminProfile = "admin-profile",
  AdminDashboards = "admin-dashboards",
  AdminUsers = "admin-users",
  AdminDoctors = "admin-doctors",
  AdminServices = "admin-services",
  AdminRequests = "admin-requests",
  AdminAppSettings = "admin-app-settings",
  AdminAppSections = "admin-app-sections",
  AdminLanguages = "admin-languages",
  AdminPrivacy = "admin-privacy",
  AdminTerms = "admin-terms",
  AdminHelp = "admin-help",
  AdminAboutUs = "admin-about-us",
  AdminTestimonial = "admin-testimonial",
  AdminTelemedicinePolicy = "admin-telemedicine-policy",
  AdminCharts = "admin-charts",
  ManageAdmins = "manage-admins",
}

export default Links;
