const { v4: uuidv4 } = require("uuid");

const servicesData = [
  {
    id: uuidv4(),
    price: 500,
    nameEn: "Imaging Consultation",
    nameAr: "استشارة تصويرية",
    shortDescriptionEn: "Short Description En goes here",
    shortDescriptionAr: "Short Description Ar goes here",
    descriptionEn: "Description En goes here",
    descriptionAr: "Description Ar goes here",
    image: "/assets/icons/services/Imaging Consultation.svg",
    whiteImage: "",
    children: [
      {
        id: uuidv4(),
        price: 0,
        nameEn: "MRI",
        nameAr: "التصوير بالرنين المغناطيسي",
        shortDescriptionEn: "",
        shortDescriptionAr: "",
        descriptionEn: "",
        descriptionAr: "",
        image: "/assets/icons/services/banner-mri blue.svg",
        whiteImage: "/assets/icons/services/banner-mri white.svg",
      },
      {
        id: uuidv4(),
        price: 0,
        nameEn: "CT",
        nameAr: "CT",
        shortDescriptionEn: "",
        shortDescriptionAr: "",
        descriptionEn: "",
        descriptionAr: "",
        image: "/assets/icons/services/banner-ct blue.svg",
        whiteImage: "/assets/icons/services/banner-ct white.svg",
      },
      {
        id: uuidv4(),
        price: 0,
        nameEn: "PET-CT",
        nameAr: "PET-CT",
        shortDescriptionEn: "",
        shortDescriptionAr: "",
        descriptionEn: "",
        descriptionAr: "",
        image: "/assets/icons/services/banner-ultrasound blue.svg",
        whiteImage: "/assets/icons/services/banner-ultrasound white.svg",
      },
      {
        id: uuidv4(),
        price: 0,
        nameEn: "X-Ray",
        nameAr: "الأشعة السينية",
        shortDescriptionEn: "",
        shortDescriptionAr: "",
        descriptionEn: "",
        descriptionAr: "",
        image: "/assets/icons/services/banner-xray blue.svg",
        whiteImage: "/assets/icons/services/banner-xray white.svg",
      },
      {
        id: uuidv4(),
        price: 0,
        nameEn: "Ultrasound",
        nameAr: "الموجات فوق الصوتية",
        shortDescriptionEn: "",
        shortDescriptionAr: "",
        descriptionEn: "",
        descriptionAr: "",
        image: "/assets/icons/services/Ultrasound blue.svg",
        whiteImage: "/assets/icons/services/Ultrasound white.svg",
      },
      {
        id: uuidv4(),
        price: 0,
        nameEn: "Mammogram",
        nameAr: "تصوير الثدي بالأشعة السينية",
        shortDescriptionEn: "",
        shortDescriptionAr: "",
        descriptionEn: "",
        descriptionAr: "",
        image: "/assets/icons/services/banner-mammogram blue.svg",
        whiteImage: "/assets/icons/services/banner-mammogram white.svg",
      },
    ],
  },
  {
    id: uuidv4(),
    price: 700,
    nameEn: "Case Consultation",
    nameAr: "استشارة حالة",
    shortDescriptionEn: "Short Description En goes here",
    shortDescriptionAr: "Short Description Ar goes here",
    descriptionEn: "Description En goes here",
    descriptionAr: "Description Ar goes here",
    image: "/assets/icons/services/Case Consultation.svg",
    whiteImage: "",
    children: [
      {
        id: uuidv4(),
        price: 0,
        nameEn: "Cardiology",
        nameAr: "طب القلب",
        shortDescriptionEn: "",
        shortDescriptionAr: "",
        descriptionEn: "",
        descriptionAr: "",
        image: "/assets/icons/services/Cardiology blue.svg",
        whiteImage: "/assets/icons/services/Cardiology white.svg",
      },
      {
        id: uuidv4(),
        price: 0,
        nameEn: "Endocrinology",
        nameAr: "طب الغدد الصماء",
        shortDescriptionEn: "",
        shortDescriptionAr: "",
        descriptionEn: "",
        descriptionAr: "",
        image: "/assets/icons/services/Endocrinology blue.svg",
        whiteImage: "/assets/icons/services/Endocrinology white.svg",
      },
      {
        id: uuidv4(),
        price: 0,
        nameEn: "Neurology",
        nameAr: "علم الأعصاب",
        shortDescriptionEn: "",
        shortDescriptionAr: "",
        descriptionEn: "",
        descriptionAr: "",
        image: "/assets/icons/services/Neurology blue.svg",
        whiteImage: "/assets/icons/services/Neurology white.svg",
      },
      {
        id: uuidv4(),
        price: 0,
        nameEn: "Oncology",
        nameAr: "علم الأورام",
        shortDescriptionEn: "",
        shortDescriptionAr: "",
        descriptionEn: "",
        descriptionAr: "",
        image: "/assets/icons/services/Oncology blue.svg",
        whiteImage: "/assets/icons/services/Oncology white.svg",
      },
      {
        id: uuidv4(),
        price: 0,
        nameEn: "Ophthalmology",
        nameAr: "طب العيون",
        shortDescriptionEn: "",
        shortDescriptionAr: "",
        descriptionEn: "",
        descriptionAr: "",
        image: "/assets/icons/services/Ophthalmology blue.svg",
        whiteImage: "/assets/icons/services/Ophthalmology white.svg",
      },
      {
        id: uuidv4(),
        price: 0,
        nameEn: "Orthopedics",
        nameAr: "طب العظام",
        shortDescriptionEn: "",
        shortDescriptionAr: "",
        descriptionEn: "",
        descriptionAr: "",
        image: "/assets/icons/services/Orthopedics blue.svg",
        whiteImage: "/assets/icons/services/Orthopedics white.svg",
      },
      {
        id: uuidv4(),
        price: 0,
        nameEn: "ENT",
        nameAr: "الأنف والأذن والحنجرة",
        shortDescriptionEn: "",
        shortDescriptionAr: "",
        descriptionEn: "",
        descriptionAr: "",
        image: "/assets/icons/services/ENT blue.svg",
        whiteImage: "/assets/icons/services/ENT white.svg",
      },
      {
        id: uuidv4(),
        price: 0,
        nameEn: "General-Surgery",
        nameAr: "الجراحة العامة",
        shortDescriptionEn: "",
        shortDescriptionAr: "",
        descriptionEn: "",
        descriptionAr: "",
        image: "/assets/icons/services/General-Surgery blue.svg",
        whiteImage: "/assets/icons/services/General-Surgery white.svg",
      },
      {
        id: uuidv4(),
        price: 0,
        nameEn: "Pathology & Laboratory",
        nameAr: "علم الأمراض والمختبر",
        shortDescriptionEn: "",
        shortDescriptionAr: "",
        descriptionEn: "",
        descriptionAr: "",
        image: "/assets/icons/services/Pathology & Labratory blue.svg",
        whiteImage: "/assets/icons/services/Pathology & Labratory white.svg",
      },
      {
        id: uuidv4(),
        price: 0,
        nameEn: "Pediatric",
        nameAr: "اخصائي اطفال",
        shortDescriptionEn: "",
        shortDescriptionAr: "",
        descriptionEn: "",
        descriptionAr: "",
        image: "/assets/icons/services/Pediatric blue.svg",
        whiteImage: "/assets/icons/services/Pediatric white.svg",
      },
      {
        id: uuidv4(),
        price: 0,
        nameEn: "Pulmonology",
        nameAr: "أمراض الرئة",
        shortDescriptionEn: "",
        shortDescriptionAr: "",
        descriptionEn: "",
        descriptionAr: "",
        image: "/assets/icons/services/Pulmonology blue.svg",
        whiteImage: "/assets/icons/services/Pulmonology white.svg",
      },
      {
        id: uuidv4(),
        price: 0,
        nameEn: "Urology",
        nameAr: "جراحة المسالك البولية",
        shortDescriptionEn: "",
        shortDescriptionAr: "",
        descriptionEn: "",
        descriptionAr: "",
        image: "/assets/icons/services/Urology blue.svg",
        whiteImage: "/assets/icons/services/Urology white.svg",
      },
      {
        id: uuidv4(),
        price: 0,
        nameEn: "Weight-Reduction",
        nameAr: "تخفيض الوزن",
        shortDescriptionEn: "",
        shortDescriptionAr: "",
        descriptionEn: "",
        descriptionAr: "",
        image: "/assets/icons/services/Weight-Reduction blue.svg",
        whiteImage: "/assets/icons/services/Weight-Reduction white.svg",
      },
    ],
  },
];

export default servicesData;
